<?php
declare(strict_types=1);

// Static registry of HTML regions the admin panel is allowed to edit.
// Each file must contain a matching pair of marker_start/marker_end HTML comments.
// 'type' controls the editor used: 'richtext' (default, Quill WYSIWYG) or 'text'
// (plain single-line input — for short labels where rich formatting makes no sense).
// 'group' organizes the admin block list by page; 'lang' tags RU/EN within a group.
return [
    'about_us_main' => [
        'group' => 'О компании',
        'lang' => 'RU',
        'label' => 'Основной текст страницы',
        'file' => __DIR__ . '/../pages/about-us-11931230.html',
        'marker_start' => '<!-- CONTENT:about_us_main:start -->',
        'marker_end' => '<!-- CONTENT:about_us_main:end -->',
    ],
    'home_about_ru' => [
        'group' => 'Главная',
        'lang' => 'RU',
        'label' => 'Блок «О нас»',
        'file' => __DIR__ . '/../index.html',
        'marker_start' => '<!-- CONTENT:home_about_ru:start -->',
        'marker_end' => '<!-- CONTENT:home_about_ru:end -->',
    ],
    'home_banner_ru' => [
        'group' => 'Главная',
        'lang' => 'RU',
        'label' => 'Баннер «Надёжный партнёр»',
        'file' => __DIR__ . '/../index.html',
        'marker_start' => '<!-- CONTENT:home_banner_ru:start -->',
        'marker_end' => '<!-- CONTENT:home_banner_ru:end -->',
    ],
    'home_about_en' => [
        'group' => 'Главная',
        'lang' => 'EN',
        'label' => 'Блок «About Us»',
        'file' => __DIR__ . '/../en/index.html',
        'marker_start' => '<!-- CONTENT:home_about_en:start -->',
        'marker_end' => '<!-- CONTENT:home_about_en:end -->',
    ],
    'home_banner_en' => [
        'group' => 'Главная',
        'lang' => 'EN',
        'label' => 'Баннер «Reliable choice»',
        'file' => __DIR__ . '/../en/index.html',
        'marker_start' => '<!-- CONTENT:home_banner_en:start -->',
        'marker_end' => '<!-- CONTENT:home_banner_en:end -->',
    ],
    'contact_intro_ru' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Вступительный текст',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_intro_ru:start -->',
        'marker_end' => '<!-- CONTENT:contact_intro_ru:end -->',
    ],
    'contact_intro_en' => [
        'group' => 'Контакты',
        'lang' => 'EN',
        'label' => 'Вступительный текст',
        'file' => __DIR__ . '/../en/pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_intro_en:start -->',
        'marker_end' => '<!-- CONTENT:contact_intro_en:end -->',
    ],
    'contact_ru_name' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Российский офис — имя',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_ru_name:start -->',
        'marker_end' => '<!-- CONTENT:contact_ru_name:end -->',
        'type' => 'text',
    ],
    'contact_ru_phone' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Российский офис — телефон',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_ru_phone:start -->',
        'marker_end' => '<!-- CONTENT:contact_ru_phone:end -->',
        'type' => 'text',
    ],
    'contact_ru_email' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Российский офис — email',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_ru_email:start -->',
        'marker_end' => '<!-- CONTENT:contact_ru_email:end -->',
        'type' => 'text',
    ],
    'contact_ru_address' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Российский офис — адрес',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_ru_address:start -->',
        'marker_end' => '<!-- CONTENT:contact_ru_address:end -->',
        'type' => 'text',
    ],
    'contact_cn_phone1_name' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Завод в Китае — телефон 1, имя',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_cn_phone1_name:start -->',
        'marker_end' => '<!-- CONTENT:contact_cn_phone1_name:end -->',
        'type' => 'text',
    ],
    'contact_cn_phone1_number' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Завод в Китае — телефон 1, номер',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_cn_phone1_number:start -->',
        'marker_end' => '<!-- CONTENT:contact_cn_phone1_number:end -->',
        'type' => 'text',
    ],
    'contact_cn_phone2_name' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Завод в Китае — телефон 2, имя',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_cn_phone2_name:start -->',
        'marker_end' => '<!-- CONTENT:contact_cn_phone2_name:end -->',
        'type' => 'text',
    ],
    'contact_cn_phone2_number' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Завод в Китае — телефон 2, номер',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_cn_phone2_number:start -->',
        'marker_end' => '<!-- CONTENT:contact_cn_phone2_number:end -->',
        'type' => 'text',
    ],
    'contact_cn_email1_name' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Завод в Китае — email 1, имя',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_cn_email1_name:start -->',
        'marker_end' => '<!-- CONTENT:contact_cn_email1_name:end -->',
        'type' => 'text',
    ],
    'contact_cn_email1_address' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Завод в Китае — email 1, адрес почты',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_cn_email1_address:start -->',
        'marker_end' => '<!-- CONTENT:contact_cn_email1_address:end -->',
        'type' => 'text',
    ],
    'contact_cn_email2_name' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Завод в Китае — email 2, имя',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_cn_email2_name:start -->',
        'marker_end' => '<!-- CONTENT:contact_cn_email2_name:end -->',
        'type' => 'text',
    ],
    'contact_cn_email2_address' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Завод в Китае — email 2, адрес почты',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_cn_email2_address:start -->',
        'marker_end' => '<!-- CONTENT:contact_cn_email2_address:end -->',
        'type' => 'text',
    ],
    'contact_cn_email3_name' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Завод в Китае — email 3, имя',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_cn_email3_name:start -->',
        'marker_end' => '<!-- CONTENT:contact_cn_email3_name:end -->',
        'type' => 'text',
    ],
    'contact_cn_email3_address' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Завод в Китае — email 3, адрес почты',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_cn_email3_address:start -->',
        'marker_end' => '<!-- CONTENT:contact_cn_email3_address:end -->',
        'type' => 'text',
    ],
    'contact_cn_address' => [
        'group' => 'Контакты',
        'lang' => 'RU',
        'label' => 'Завод в Китае — адрес',
        'file' => __DIR__ . '/../pages/contactus.html',
        'marker_start' => '<!-- CONTENT:contact_cn_address:start -->',
        'marker_end' => '<!-- CONTENT:contact_cn_address:end -->',
        'type' => 'text',
    ],
    'workshop_ru_1' => [
        'group' => 'Подразделения компании',
        'lang' => 'RU',
        'label' => 'Цех намотки проводов',
        'file' => __DIR__ . '/../pages/Подразделения-компании-11932328.html',
        'marker_start' => '<!-- CONTENT:workshop_ru_1:start -->',
        'marker_end' => '<!-- CONTENT:workshop_ru_1:end -->',
        'type' => 'text',
    ],
    'workshop_ru_2' => [
        'group' => 'Подразделения компании',
        'lang' => 'RU',
        'label' => 'Цех нанесения покрытия',
        'file' => __DIR__ . '/../pages/Подразделения-компании-11932328.html',
        'marker_start' => '<!-- CONTENT:workshop_ru_2:start -->',
        'marker_end' => '<!-- CONTENT:workshop_ru_2:end -->',
        'type' => 'text',
    ],
    'workshop_ru_3' => [
        'group' => 'Подразделения компании',
        'lang' => 'RU',
        'label' => 'Цех точного механического обработки',
        'file' => __DIR__ . '/../pages/Подразделения-компании-11932328.html',
        'marker_start' => '<!-- CONTENT:workshop_ru_3:start -->',
        'marker_end' => '<!-- CONTENT:workshop_ru_3:end -->',
        'type' => 'text',
    ],
    'workshop_ru_4' => [
        'group' => 'Подразделения компании',
        'lang' => 'RU',
        'label' => 'Склад хранения кремнистой стали',
        'file' => __DIR__ . '/../pages/Подразделения-компании-11932328.html',
        'marker_start' => '<!-- CONTENT:workshop_ru_4:start -->',
        'marker_end' => '<!-- CONTENT:workshop_ru_4:end -->',
        'type' => 'text',
    ],
    'workshop_ru_5' => [
        'group' => 'Подразделения компании',
        'lang' => 'RU',
        'label' => 'Цех сборки',
        'file' => __DIR__ . '/../pages/Подразделения-компании-11932328.html',
        'marker_start' => '<!-- CONTENT:workshop_ru_5:start -->',
        'marker_end' => '<!-- CONTENT:workshop_ru_5:end -->',
        'type' => 'text',
    ],
    'workshop_ru_6' => [
        'group' => 'Подразделения компании',
        'lang' => 'RU',
        'label' => 'Цех динамического балансирования',
        'file' => __DIR__ . '/../pages/Подразделения-компании-11932328.html',
        'marker_start' => '<!-- CONTENT:workshop_ru_6:start -->',
        'marker_end' => '<!-- CONTENT:workshop_ru_6:end -->',
        'type' => 'text',
    ],
    'workshop_ru_7' => [
        'group' => 'Подразделения компании',
        'lang' => 'RU',
        'label' => 'Цех кремнистой стали',
        'file' => __DIR__ . '/../pages/Подразделения-компании-11932328.html',
        'marker_start' => '<!-- CONTENT:workshop_ru_7:start -->',
        'marker_end' => '<!-- CONTENT:workshop_ru_7:end -->',
        'type' => 'text',
    ],
    'workshop_en_1' => [
        'group' => 'Подразделения компании',
        'lang' => 'EN',
        'label' => 'Wire Embedding Workshop',
        'file' => __DIR__ . '/../en/pages/Workshop-Display-11911461.html',
        'marker_start' => '<!-- CONTENT:workshop_en_1:start -->',
        'marker_end' => '<!-- CONTENT:workshop_en_1:end -->',
        'type' => 'text',
    ],
    'workshop_en_2' => [
        'group' => 'Подразделения компании',
        'lang' => 'EN',
        'label' => 'Immersion Paint Workshop',
        'file' => __DIR__ . '/../en/pages/Workshop-Display-11911461.html',
        'marker_start' => '<!-- CONTENT:workshop_en_2:start -->',
        'marker_end' => '<!-- CONTENT:workshop_en_2:end -->',
        'type' => 'text',
    ],
    'workshop_en_3' => [
        'group' => 'Подразделения компании',
        'lang' => 'EN',
        'label' => 'Precision machining workshop',
        'file' => __DIR__ . '/../en/pages/Workshop-Display-11911461.html',
        'marker_start' => '<!-- CONTENT:workshop_en_3:start -->',
        'marker_end' => '<!-- CONTENT:workshop_en_3:end -->',
        'type' => 'text',
    ],
    'workshop_en_4' => [
        'group' => 'Подразделения компании',
        'lang' => 'EN',
        'label' => 'Sufficient Storage of Silicon Steel Sheets',
        'file' => __DIR__ . '/../en/pages/Workshop-Display-11911461.html',
        'marker_start' => '<!-- CONTENT:workshop_en_4:start -->',
        'marker_end' => '<!-- CONTENT:workshop_en_4:end -->',
        'type' => 'text',
    ],
    'workshop_en_5' => [
        'group' => 'Подразделения компании',
        'lang' => 'EN',
        'label' => 'Assembly Line Workshop',
        'file' => __DIR__ . '/../en/pages/Workshop-Display-11911461.html',
        'marker_start' => '<!-- CONTENT:workshop_en_5:start -->',
        'marker_end' => '<!-- CONTENT:workshop_en_5:end -->',
        'type' => 'text',
    ],
    'workshop_en_6' => [
        'group' => 'Подразделения компании',
        'lang' => 'EN',
        'label' => 'Dynamic Balance Testing Workshop',
        'file' => __DIR__ . '/../en/pages/Workshop-Display-11911461.html',
        'marker_start' => '<!-- CONTENT:workshop_en_6:start -->',
        'marker_end' => '<!-- CONTENT:workshop_en_6:end -->',
        'type' => 'text',
    ],
    'workshop_en_7' => [
        'group' => 'Подразделения компании',
        'lang' => 'EN',
        'label' => 'Silicon Steel Sheet Workshop',
        'file' => __DIR__ . '/../en/pages/Workshop-Display-11911461.html',
        'marker_start' => '<!-- CONTENT:workshop_en_7:start -->',
        'marker_end' => '<!-- CONTENT:workshop_en_7:end -->',
        'type' => 'text',
    ],
    'privacy_policy_ru' => [
        'group' => 'Политика конфиденциальности',
        'lang' => 'RU',
        'label' => 'Текст страницы',
        'file' => __DIR__ . '/../pages/privacy-policy.html',
        'marker_start' => '<!-- CONTENT:privacy_policy_ru:start -->',
        'marker_end' => '<!-- CONTENT:privacy_policy_ru:end -->',
    ],
    'privacy_policy_en' => [
        'group' => 'Политика конфиденциальности',
        'lang' => 'EN',
        'label' => 'Текст страницы',
        'file' => __DIR__ . '/../en/pages/privacy-policy-11909901.html',
        'marker_start' => '<!-- CONTENT:privacy_policy_en:start -->',
        'marker_end' => '<!-- CONTENT:privacy_policy_en:end -->',
    ],
    'user_agreement_ru' => [
        'group' => 'Пользовательское соглашение',
        'lang' => 'RU',
        'label' => 'Текст страницы',
        'file' => __DIR__ . '/../pages/user-agreement.html',
        'marker_start' => '<!-- CONTENT:user_agreement_ru:start -->',
        'marker_end' => '<!-- CONTENT:user_agreement_ru:end -->',
    ],
    'user_agreement_en' => [
        'group' => 'Пользовательское соглашение',
        'lang' => 'EN',
        'label' => 'Текст страницы',
        'file' => __DIR__ . '/../en/pages/user-agreement.html',
        'marker_start' => '<!-- CONTENT:user_agreement_en:start -->',
        'marker_end' => '<!-- CONTENT:user_agreement_en:end -->',
    ],
    'personal_data_policy_ru' => [
        'group' => 'Политика персональных данных',
        'lang' => 'RU',
        'label' => 'Текст страницы',
        'file' => __DIR__ . '/../pages/personal-data-policy.html',
        'marker_start' => '<!-- CONTENT:personal_data_policy_ru:start -->',
        'marker_end' => '<!-- CONTENT:personal_data_policy_ru:end -->',
    ],
    'personal_data_policy_en' => [
        'group' => 'Политика персональных данных',
        'lang' => 'EN',
        'label' => 'Текст страницы',
        'file' => __DIR__ . '/../en/pages/personal-data-policy.html',
        'marker_start' => '<!-- CONTENT:personal_data_policy_en:start -->',
        'marker_end' => '<!-- CONTENT:personal_data_policy_en:end -->',
    ],
];
